import { useEffect, useMemo, useState } from "react";
import { api } from "../api/client";
import type { User } from "../types";

type Tab="requests"|"members"|"roles"|"violations"|"updates";
type AdminRequest={id:number;type:string;status:string;amount?:number;title:string;details?:string;user_email:string;user_name:string;created_at:string};
type Role={role_key:string;name:string;permissions:Record<string,boolean>;is_owner?:number};
type Member={id:number;email:string;name:string;role:string;account_status:string;created_at:string};
type Violation={id:number;email:string;name:string;reason:string;severity:string;account_status:string};
type SiteUpdate={id:number|string;title:string;body:string;created_at:string};
const PERMS=["access_admin","manage_requests","manage_roles","manage_members","manage_announcements","ban_users"];
const blankPerms=()=>Object.fromEntries(PERMS.map(p=>[p,false])) as Record<string,boolean>;
const keyToBytes=(key:string)=>{const pad="=".repeat((4-key.length%4)%4);const raw=atob((key+pad).replace(/-/g,"+").replace(/_/g,"/"));return Uint8Array.from([...raw].map(c=>c.charCodeAt(0)));};

export default function AdminPanel({currentUser,notify}:{currentUser:User|null;notify:(msg:string,icon?:string,ok?:boolean)=>void}) {
  const[tab,setTab]=useState<Tab>("requests"),[loading,setLoading]=useState(true),[error,setError]=useState("");
  const[requests,setRequests]=useState<AdminRequest[]>([]),[roles,setRoles]=useState<Role[]>([]),[members,setMembers]=useState<Member[]>([]),[violations,setViolations]=useState<Violation[]>([]),[updates,setUpdates]=useState<SiteUpdate[]>([]);
  const[email,setEmail]=useState(""),[memberRole,setMemberRole]=useState("admin"),[roleName,setRoleName]=useState(""),[rolePerms,setRolePerms]=useState<Record<string,boolean>>(blankPerms());
  const[announceTitle,setAnnounceTitle]=useState(""),[announceBody,setAnnounceBody]=useState("");
  const canOwner=currentUser?.role==="owner";
  const pendingCount=useMemo(()=>requests.filter(r=>r.status==="pending").length,[requests]);
  const refreshAdminData=async({showLoading=true,showError=true}={showLoading:true,showError:true})=>{if(showLoading) setLoading(true);if(showError) setError("");try{const d=await api.get("/admin/summary");setRequests(d.requests||[]);setRoles(d.roles||[]);setMembers(d.members||[]);setViolations(d.violations||[]);setUpdates(d.updates||[]);}catch(e:any){if(showError) setError(e.message||"Admin access unavailable");}finally{if(showLoading) setLoading(false);}};
  useEffect(()=>{refreshAdminData();const id=setInterval(()=>refreshAdminData({showLoading:false,showError:false}),30000);return()=>clearInterval(id);},[]);
  const decide=async(id:number,action:"approve"|"reject")=>{try{await api.patch(`/admin/requests/${id}`,{action});notify(`Request ${action}d`,action==="approve"?"OK":"!");refreshAdminData({showLoading:false,showError:false});}catch(e:any){notify(e.message,"!",false);}};
  const addMember=async()=>{try{await api.post("/admin/members",{email,role:memberRole});setEmail("");notify("Member role updated","OK");refreshAdminData({showLoading:false,showError:false});}catch(e:any){notify(e.message,"!",false);}};
  const revoke=async(id:number)=>{try{await api.patch(`/admin/members/${id}/role`,{role:"user"});notify("Admin privileges revoked","OK");refreshAdminData({showLoading:false,showError:false});}catch(e:any){notify(e.message,"!",false);}};
  const ban=async(id:number,reason="Terms violation")=>{try{await api.patch(`/admin/members/${id}/ban`,{reason});notify("User banned and logged out","!");refreshAdminData({showLoading:false,showError:false});}catch(e:any){notify(e.message,"!",false);}};
  const restore=async(id:number)=>{try{await api.patch(`/admin/members/${id}/restore`,{});notify("User restored","OK");refreshAdminData({showLoading:false,showError:false});}catch(e:any){notify(e.message,"!",false);}};
  const createRole=async()=>{try{await api.post("/admin/roles",{name:roleName,permissions:rolePerms});setRoleName("");setRolePerms(blankPerms());notify("Role created","OK");load();}catch(e:any){notify(e.message,"!",false);}};
  const sendAnnouncement=async()=>{try{await api.post("/admin/announcements",{title:announceTitle,body:announceBody});setAnnounceTitle("");setAnnounceBody("");notify("Platform update sent","OK");load();}catch(e:any){notify(e.message,"!",false);}};
  const enablePush=async()=>{try{if(!("serviceWorker" in navigator)||!("PushManager" in window))throw new Error("Push is not supported here");const cfg=await api.get("/admin/push/config");if(!cfg.publicKey)throw new Error("Set VAPID_PUBLIC_KEY and VAPID_PRIVATE_KEY on the backend");const reg=await navigator.serviceWorker.register("/sw.js");const existing=await reg.pushManager.getSubscription();const sub=existing||await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:keyToBytes(cfg.publicKey)});await api.post("/admin/push/subscribe",sub);notify("This admin device will receive alerts","OK");}catch(e:any){notify(e.message,"!",false);}};
  if(error)return <div className="gcard admin-denied"><div className="stitle">Admin Center</div><p className="admin-note">{error}</p></div>;
  return <div><div className="topbar"><div><div className="ttl">Admin Center</div><div className="tdate">Requests, roles, admins, violations, and platform updates.</div></div><button className="btn btn-primary" onClick={enablePush}>Enable device alerts</button></div><div className="admin-banner"><b>{pendingCount}</b> pending request(s). Alerts go only to devices subscribed by active admins.</div><div className="admin-tabs">{(["requests","members","roles","violations","updates"] as Tab[]).map(x=><button key={x} className={`chip ${tab===x?"active":""}`} onClick={()=>setTab(x)}>{x}</button>)}</div>{loading?<div className="gcard">Loading admin data...</div>:<>
    {tab==="requests"&&<div className="gcard admin-table-wrap"><table className="admin-table"><thead><tr><th>Request</th><th>User</th><th>Status</th><th>Amount</th><th>Created</th><th></th></tr></thead><tbody>{requests.map(r=><tr key={r.id}><td><b style={{color:"var(--text)"}}>{r.title}</b><div className="admin-note">{r.details||r.type}</div></td><td>{r.user_name}<div className="admin-note">{r.user_email}</div></td><td><span className={`admin-status ${r.status}`}>{r.status}</span></td><td>{r.amount?`$${Number(r.amount).toLocaleString()}`:"-"}</td><td>{new Date(r.created_at).toLocaleString()}</td><td>{r.status==="pending"&&<div style={{display:"flex",gap:8}}><button className="btn btn-action btn-sm" onClick={()=>decide(r.id,"approve")}>Approve</button><button className="btn btn-danger btn-sm" onClick={()=>decide(r.id,"reject")}>Reject</button></div>}</td></tr>)}</tbody></table></div>}
    {tab==="members"&&<div className="admin-grid"><div className="gcard admin-table-wrap"><table className="admin-table"><tbody>{members.map(m=><tr key={m.id}><td>{m.name}<div className="admin-note">{m.email}</div></td><td>{m.role}</td><td><span className={`admin-status ${m.account_status}`}>{m.account_status}</span></td><td><div style={{display:"flex",gap:8,flexWrap:"wrap"}}>{canOwner&&m.role!=="owner"&&<button className="btn btn-ghost btn-sm" onClick={()=>revoke(m.id)}>Revoke admin</button>}{canOwner&&m.role!="owner"&&(m.account_status==="banned"?<button className="btn btn-action btn-sm" onClick={()=>restore(m.id)}>Restore</button>:<button className="btn btn-danger btn-sm" onClick={()=>ban(m.id)}>Ban</button>)}</div></td></tr>)}</tbody></table></div><div className="gcard"><div className="stitle">Add member</div><div className="admin-form-grid"><input className="inp" placeholder="member@email.com" value={email} onChange={e=>setEmail(e.target.value)}/><select className="sel" value={memberRole} onChange={e=>setMemberRole(e.target.value)}>{roles.filter(r=>!r.is_owner).map(r=><option key={r.role_key} value={r.role_key}>{r.name}</option>)}</select><button className="btn btn-primary admin-plus" onClick={addMember}>+</button></div></div></div>}
    {tab==="roles"&&<div className="admin-grid"><div className="gcard admin-card-list">{roles.map(r=><div key={r.role_key} className="admin-banner"><b>{r.name}</b><div className="admin-note">{Object.entries(r.permissions||{}).filter(([,v])=>v).map(([k])=>k).join(", ")||"No permissions"}</div></div>)}</div><div className="gcard"><div className="stitle">Create role</div><input className="inp" placeholder="Role name" value={roleName} onChange={e=>setRoleName(e.target.value)}/><div className="admin-perms">{PERMS.map(p=><label key={p} className="admin-perm"><input type="checkbox" checked={!!rolePerms[p]} onChange={e=>setRolePerms(v=>({...v,[p]:e.target.checked}))}/>{p}</label>)}</div><button className="btn btn-primary" style={{marginTop:14,width:"100%"}} onClick={createRole} disabled={!canOwner}>Create role</button></div></div>}
    {tab==="violations"&&<div className="gcard admin-table-wrap"><table className="admin-table"><tbody>{violations.map(v=><tr key={v.id}><td>{v.name}<div className="admin-note">{v.email}</div></td><td>{v.reason}</td><td>{v.severity}</td><td><span className={`admin-status ${v.account_status}`}>{v.account_status}</span></td><td>{v.account_status==="banned"?<button className="btn btn-action btn-sm" onClick={()=>restore(v.id)}>Restore</button>:<button className="btn btn-danger btn-sm" onClick={()=>ban(v.id,v.reason)}>Ban</button>}</td></tr>)}</tbody></table></div>}
    {tab==="updates"&&<div className="admin-grid"><div className="gcard admin-card-list">{updates.map(u=><div className="admin-banner" key={u.id}><b>{u.title}</b><div className="admin-note">{u.body}</div><div className="admin-note">{new Date(u.created_at).toLocaleString()}</div></div>)}</div><div className="gcard"><div className="stitle">Send platform update</div><input className="inp" placeholder="Improved bug fixes" value={announceTitle} onChange={e=>setAnnounceTitle(e.target.value)} style={{marginBottom:10}}/><textarea className="inp" placeholder="Write the announcement..." value={announceBody} onChange={e=>setAnnounceBody(e.target.value)} style={{minHeight:130,resize:"vertical",marginBottom:12}}/><button className="btn btn-primary" style={{width:"100%"}} onClick={sendAnnouncement}>Send update</button></div></div>}
  </>}</div>;
}
