const router=require("express").Router();
const { queryOne, queryAll, execute }=require("../db");
const { requirePermission, requireOwner }=require("../middleware/auth");
const { notifyAdmins, configured }=require("../services/push");
const slug=s=>String(s||"").trim().toLowerCase().replace(/[^a-z0-9]+/g,"_").replace(/^_+|_+$/g,"").slice(0,40)||"role";
const parse=v=>{try{return JSON.parse(v||"{}");}catch{return {};}};
async function applyRequest(r,admin,action,note){if(r.status!=="pending")throw new Error("Request already reviewed");if(action==="approve"){if(r.type==="deposit"){const amt=Number(r.amount||0);await execute("UPDATE users SET cash_balance=cash_balance+?,updated_at=datetime('now') WHERE id=?",[amt,r.user_id]);await execute("INSERT INTO transactions (user_id,type,symbol,amount,price,fee,total,status) VALUES (?,?,?,?,?,?,?,'completed')",[r.user_id,"deposit","USD",amt,1,0,amt]);}else if(r.type==="kyc"){const p=parse(r.payload);if(p.kind==="id")await execute("UPDATE users SET kyc_id_status='verified',updated_at=datetime('now') WHERE id=?",[r.user_id]);if(p.kind==="address")await execute("UPDATE users SET kyc_addr_status='verified',updated_at=datetime('now') WHERE id=?",[r.user_id]);}else if(r.type==="account_deletion"){await execute("DELETE FROM refresh_tokens WHERE user_id=?",[r.user_id]);await execute("DELETE FROM sessions WHERE user_id=?",[r.user_id]);await execute("DELETE FROM push_subscriptions WHERE user_id=?",[r.user_id]);await execute("DELETE FROM users WHERE id=?",[r.user_id]);}}await execute("UPDATE admin_requests SET status=?,reviewed_by=?,reviewed_by_email=?,reviewed_at=datetime('now'),admin_note=? WHERE id=?",[action==="approve"?"approved":"rejected",admin.id,admin.email,note||null,r.id]);}
router.get("/summary",requirePermission("access_admin"),async(req,res)=>{try{const requests=await queryAll("SELECT * FROM admin_requests ORDER BY CASE status WHEN 'pending' THEN 0 ELSE 1 END, created_at DESC LIMIT 100");const roles=(await queryAll("SELECT role_key,name,permissions,is_owner FROM roles ORDER BY is_owner DESC,name")).map(r=>({...r,permissions:parse(r.permissions)}));const adminRoleRows=await queryAll("SELECT role_key FROM roles WHERE is_owner=1 OR permissions LIKE '%\"access_admin\":true%' ORDER BY role_key");const adminRoles=adminRoleRows.map(r=>r.role_key).filter(Boolean);const members=adminRoles.length ? await queryAll(`SELECT id,email,name,role,account_status,created_at FROM users WHERE role IN (${adminRoles.map(()=>"?").join(",")}) ORDER BY CASE role WHEN 'owner' THEN 0 WHEN 'admin' THEN 1 ELSE 2 END, created_at DESC LIMIT 200`, adminRoles) : [];const updates=await queryAll("SELECT id,title,body,created_at FROM site_updates ORDER BY created_at DESC LIMIT 20");const violations=await queryAll(`SELECT u.id,u.email,u.name,u.account_status,'Multiple rejected admin requests' AS reason,'medium' AS severity FROM users u JOIN admin_requests ar ON ar.user_id=u.id AND ar.status='rejected' GROUP BY u.id HAVING COUNT(ar.id)>=3 UNION ALL SELECT id,email,name,account_status,COALESCE(ban_reason,'Account is terminated') AS reason,'high' AS severity FROM users WHERE account_status='banned'`);res.json({requests,roles,members,updates,violations});}catch(err){res.status(500).json({error:err.message});}});
router.patch("/requests/:id",requirePermission("manage_requests"),async(req,res)=>{try{const action=req.body.action;if(!["approve","reject"].includes(action))return res.status(400).json({error:"Action must be approve or reject"});const r=await queryOne("SELECT * FROM admin_requests WHERE id=?",[req.params.id]);if(!r)return res.status(404).json({error:"Request not found"});await applyRequest(r,req.user,action,req.body.note);res.json({message:`Request ${action}d`});}catch(err){res.status(500).json({error:err.message});}});
router.post("/announcements",requirePermission("manage_announcements"),async(req,res)=>{try{const title=String(req.body.title||"").trim(),body=String(req.body.body||"").trim();if(!title||!body)return res.status(400).json({error:"Title and body are required"});await execute("INSERT INTO site_updates (title,body) VALUES (?,?)",[title,body]);await notifyAdmins({title:"Platform update",body,url:"/"});res.status(201).json({message:"Announcement posted"});}catch(err){res.status(500).json({error:err.message});}});
router.post("/roles",requireOwner,async(req,res)=>{try{const name=String(req.body.name||"").trim();if(!name)return res.status(400).json({error:"Role name required"});const key=slug(name);await execute("INSERT INTO roles (role_key,name,permissions) VALUES (?,?,?)",[key,name,JSON.stringify(req.body.permissions||{})]);res.status(201).json({message:"Role created",role_key:key});}catch(err){res.status(500).json({error:err.message});}});
router.post("/members",requireOwner,async(req,res)=>{try{const email=String(req.body.email||"").trim().toLowerCase(),role=String(req.body.role||"user");const user=await queryOne("SELECT id,role FROM users WHERE email=?",[email]);if(!user)return res.status(404).json({error:"User must create an account before you can add them"});if(user.role==="owner")return res.status(400).json({error:"Owner role cannot be changed"});const targetRole=await queryOne("SELECT role_key,is_owner FROM roles WHERE role_key=?",[role]);if(!targetRole||targetRole.is_owner)return res.status(400).json({error:"Choose a valid non-owner role"});await execute("UPDATE users SET role=?,updated_at=datetime('now') WHERE id=?",[role,user.id]);res.json({message:"Member role updated"});}catch(err){res.status(500).json({error:err.message});}});
router.patch("/members/:id/role",requireOwner,async(req,res)=>{try{const role=String(req.body.role||"user");const user=await queryOne("SELECT role FROM users WHERE id=?",[req.params.id]);if(!user)return res.status(404).json({error:"User not found"});if(user.role==="owner")return res.status(400).json({error:"Owner role cannot be changed"});const targetRole=await queryOne("SELECT role_key,is_owner FROM roles WHERE role_key=?",[role]);if(!targetRole||targetRole.is_owner)return res.status(400).json({error:"Choose a valid non-owner role"});await execute("UPDATE users SET role=?,updated_at=datetime('now') WHERE id=?",[role,req.params.id]);if(role==="user")await execute("DELETE FROM push_subscriptions WHERE user_id=?",[req.params.id]);res.json({message:"Role updated"});}catch(err){res.status(500).json({error:err.message});}});
router.patch("/members/:id/ban",requireOwner,async(req,res)=>{try{const user=await queryOne("SELECT role FROM users WHERE id=?",[req.params.id]);if(!user)return res.status(404).json({error:"User not found"});if(user.role==="owner")return res.status(400).json({error:"Owner cannot be banned"});const reason=String(req.body.reason||"You have violated our terms and conditions and your account is terminated").slice(0,240);await execute("UPDATE users SET account_status='banned',ban_reason=?,updated_at=datetime('now') WHERE id=?",[reason,req.params.id]);await execute("DELETE FROM refresh_tokens WHERE user_id=?",[req.params.id]);await execute("UPDATE sessions SET logout_at=datetime('now') WHERE user_id=? AND logout_at IS NULL",[req.params.id]);res.json({message:"User banned"});}catch(err){res.status(500).json({error:err.message});}});
router.patch("/members/:id/restore",requireOwner,async(req,res)=>{try{await execute("UPDATE users SET account_status='active',ban_reason=NULL,updated_at=datetime('now') WHERE id=?",[req.params.id]);res.json({message:"User restored"});}catch(err){res.status(500).json({error:err.message});}});
router.get("/push/config",requirePermission("access_admin"),(req,res)=>res.json({publicKey:process.env.VAPID_PUBLIC_KEY||"",enabled:configured()}));
router.post("/push/subscribe",requirePermission("access_admin"),async(req,res)=>{try{if(!req.body?.endpoint)return res.status(400).json({error:"Invalid push subscription"});await execute("INSERT INTO push_subscriptions (user_id,endpoint,subscription_json) VALUES (?,?,?) ON CONFLICT(endpoint) DO UPDATE SET user_id=excluded.user_id,subscription_json=excluded.subscription_json,updated_at=datetime('now')",[req.user.id,req.body.endpoint,JSON.stringify(req.body)]);res.status(201).json({message:"Push subscription saved"});}catch(err){res.status(500).json({error:err.message});}});
module.exports=router;
